name: deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # specify the `main` branch as the remote branch to push to
          branch: main
          git_remote_url: ssh://dokku@159.112.177.194/dash
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Ensure SSH directory exists
        run: mkdir -p ~/.ssh

      - name: Add Dokku host to known_hosts
        run: |
          ssh-keyscan -H "m4rc310.com.br" >> ~/.ssh/known_hosts

      - name: Deploy to Dokku
        env:
          DOKKU_HOST: m4rc310.com.br
          DOKKU_APP: dashboard
          DOKKU_USER: dokku
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-agent bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY\") && git remote add dokku dokku@$DOKKU_HOST:$DOKKU_APP && git push dokku master:v0.0.8"