name: Deploy Action

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Dokku host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "m4rc310.com.br" >> ~/.ssh/known_hosts

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ssh://dokku@m4rc310.com.br/dash
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Dokku
        env:
          DOKKU_HOST: m4rc310.com.br
          DOKKU_APP: dash
          DOKKU_USER: dokku
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          git remote add dokku dokku@m4rc310.com.br:dash
          git push dokku master