name: deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # specify the `main` branch as the remote branch to push to
          branch: main
          git_remote_url: ssh://dokku@159.112.177.194/dash
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Push to dokku
        run: |
          git remote add dokku ssh://dokku@m4rc310.com.br/dash
          git push dokku master:v0.0.8