name: CI/CD Pipeline

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Ensure SSH directory exists
        run: mkdir -p ~/.ssh

      - name: Add Dokku host to known_hosts
        run: |
          ssh-keyscan -H "m4rc310.com.br" >> ~/.ssh/known_hosts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get Tag Name
        id: tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Add Dokku remote and push code
        env:
          DOKKU_HOST: m4rc310.com.br
          DOKKU_APP: dash
          DOKKU_USER: dokku
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          git remote add dokku dokku@$DOKKU_HOST:$DOKKU_APP
          git push -f dokku refs/tags/${{ steps.tag.outputs.tag_name }}:refs/tags/${{ steps.tag.outputs.tag_name }}